config/routes.rb
GestionOpticaArena::Application.routes.draw do
  devise_for :users
  resources :work_orders do
    collection do
      get :find_items
      get :import_file
    end
  end

  resources :clients do
    collection do
      get :find_items
    end
    resources :work_orders
  end

  root :to => 'main#index'

end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  address      :string(255)
#  phone_number :string(255)
#  city         :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#  surname      :string(255)
#  email        :string(255)
#  comments     :string(255)
#

# -*- encoding : utf-8 -*-
class Client < ActiveRecord::Base
  attr_accessible :name, :surname, :address, :phone_number, :email, :city, :comments
  cattr_reader :per_page
  @@per_page = 10
  validates_presence_of :name, :surname
  validates_uniqueness_of :name, :scope => :surname
  validates_uniqueness_of :email, :allow_blank => true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :allow_blank => true

  has_many :work_orders

  def self.search(search, page)
    where(
        'name LIKE ?
        OR surname LIKE ?
        OR CONCAT(name, \' \', surname) LIKE ?
        OR CONCAT(surname, \', \', name) LIKE ?
        OR address LIKE ?
        OR phone_number LIKE ?
        OR email LIKE ?
        OR city LIKE ?',
        "%#{search}%", "%#{search}%", "%#{search}%",
        "%#{search}%", "%#{search}%", "%#{search}%",
        "%#{search}%", "%#{search}%"
    ).paginate(
        :page => page
    )
  end

  def full_name
    "#{name} #{surname}"
  end

end

app/controllers/clients_controller.rb
# -*- encoding : utf-8 -*-
class ClientsController < ApplicationController
  # GET /clients
  # GET /clients.xml
  def index
    @clients = Client.search params[:search], params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.xml
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.xml
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.xml
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        flash[:notice] = 'El cliente ha sido creado con éxito.'
        format.html { redirect_to(@client) }
        format.xml  { render :xml => @client, :status => :created, :location => @client }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.xml
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        flash[:notice] = 'El cliente ha sido editado con éxito.'
        format.html { redirect_to(@client) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @client.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.xml
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to(clients_url) }
      format.xml  { head :ok }
    end
  end

  def find_items
    @clients = Client.search params[:search], params[:page]
    render :partial => 'search'
  end
end

app/helpers/clients_helper.rb
# -*- encoding : utf-8 -*-
module ClientsHelper
end

app/views/clients/_form.html.erb
<table class="table table-striped">
  <tr>
    <td><%= form.label :name, _("Name:") %></td>
    <td><%= form.text_field :name, class: 'form-control' %></td>
  </tr>
  <tr>
    <td><%= form.label :surname, _("Surname:") %></td>
    <td><%= form.text_field :surname, class: 'form-control' %></td>
  </tr>
  <tr>
    <td><%= label_tag :client_address, _("Address:") %></td>
    <td><%= form.text_field :address, class: 'form-control' %></td>
  </tr>
  <tr>
    <td><%= label_tag :client_city, _("City:") %></td>
    <td><%= form.text_field :city, class: 'form-control' %></td>
  </tr>
  <tr>
    <td><%= label_tag :client_phone_number, _("Phone(s):") %></td>
    <td><%= form.text_field :phone_number, class: 'form-control' %></td>
  </tr>
  <tr>
    <td><%= label_tag :email, _("Email:") %></td>
    <td><%= form.text_field :email, class: 'form-control' %></td>
  </tr>
  <tr>
    <td><%= label_tag :client_comments, _("Observations:") %></td>
    <td><%= form.text_field :comments, class: 'form-control' %></td>
  </tr>
</table>

app/views/clients/_search.html.erb
<div class="table-responsive">
  <table class="table table-striped">
      <tr>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Domicilio</th>
        <th>Localidad</th>
        <th>Télefonos</th>
        <th>Correo electrónico</th>
        <th>Observaciones</th>
        <th colspan="3">Acciones</th>
        <th>Trabajos</th>
      </tr>

    <% for client in @clients %>
      <tr>
        <td><%=h client.name %></td>
        <td><%=h client.surname %></td>
        <td><%=h client.address %></td>
        <td><%=h client.city %></td>
        <td><%=h client.phone_number %></td>
        <td><%=h client.email %></td>
        <td><%=h client.comments %></td>
        <td><%= link_to 'Ver', client %></td>
        <td><%= link_to 'Editar', edit_client_path(client) %></td>
        <td><%= link_to 'Borrar', client, data: {confirm: "¿Está seguro de borrar al client #{client.name}?"}, :method => :delete %></td>
        <td class="jobs"><%= link_to 'Órdenes de trabajo', client_work_orders_path(client) %></td>
      </tr>
    <% end %>
    </table>
</div>
<% params[:action] = "index" %>
<%= will_paginate @clients, :prev_label => "&laquo; Anterior", :next_label => "Siguiente &raquo;" %>

app/views/clients/edit.html.erb
<% @title = "Editar client" %>
<% @navbar = [link_to('<span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Clients'.html_safe, clients_path), @title] %>

<%= error_messages_for :client %>

<div class="table-responsive tblclient">
  <%= form_for(@client) do |form| %>
      <%= render :partial => 'form', :object => form %>
      <%= form.submit 'Guardar edición client', :class => 'btn btn-warning pull-right' %>
      <%= link_to '<span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;&nbsp;Volver atrás'.html_safe, clients_path %>
  <% end %>
</div>

app/views/clients/index.html.erb
<% @title = "Clients" %>
<% @navbar = ['<span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Clients'.html_safe] %>

<%= render :partial => "shared/search_field" %>
<div id="search_results">
  <%= render :partial => "search" %>
</div>

app/views/clients/new.html.erb
<% @title = "Nuevo client" %>
<% @navbar = [link_to('<span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Clients'.html_safe, clients_path), @title] %>

<%= error_messages_for :client %>

<div class="table-responsive tblclient">
  <%= form_for(@client) do |form| %>
      <%= render :partial => 'form', :object => form %>
      <%= form.submit 'Crear', :class => 'btn btn-warning pull-right' %>
  <% end %>

  <%= link_to '<span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;&nbsp;Volver atrás'.html_safe, clients_path %>
</div>

app/views/clients/show.html.erb
<% @title = "Mostrar client" %>
<% @navbar = [link_to('<span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Clients'.html_safe, clients_path), @title] %>

<div class="table-responsive tblclient">
  <div>
    <%= link_to '<span class="print_link glyphicon glyphicon-print"></span>&nbsp;&nbsp;Imprimir client'.html_safe, 'javascript:window.print()', class: 'print' %>
  </div>
  <br />
  <h3 class="page-title">Datos del client</h3>
  <table class="table table-striped">
    <tr>
      <td><b>Nombre:</b></td>
      <td><%= @client.full_name %></td>
    </tr>
    <tr>
      <td><b>Domicilio:</b></td>
      <td><%= @client.address %></td>
    </tr>
    <tr>
      <td><b>Localidad:</b></td>
      <td><%= @client.city %></td>
    </tr>
    <tr>
      <td><b>Teléfono:</b></td>
      <td><%= @client.phone_number %></td>
    </tr>
    <tr>
      <td><b>Correo electrónico:</b></td>
      <td><%= @client.email %></td>
    </tr>
    <tr>
      <td><b>Observaciones:</b></td>
      <td><%= @client.comments %></td>
    </tr>
  </table>

  <div class="print_link">
    <%= link_to '<span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;&nbsp;Volver atrás'.html_safe, clients_path %>
    <%= link_to 'Editar client', edit_client_path(@client), :class => 'btn btn-warning pull-right' %>
  </div>
</div>