config/routes.rb
GestionOpticaArena::Application.routes.draw do
  devise_for :users
  resources :work_orders do
    collection do
      get :find_items
      get :import_file
    end
  end

  resources :clients do
    collection do
      get :find_items
    end
    resources :work_orders
  end

  root :to => 'main#index'

end

app/models/work_order.rb
# == Schema Information
#
# Table name: work_orders
#
#  id                      :integer          not null, primary key
#  description             :string(255)
#  date                    :date
#  delivery_date           :date
#  order_number            :integer
#  distance_right_sph      :decimal(10, 2)   default(0.0)
#  distance_right_cyl      :decimal(10, 2)   default(0.0)
#  distance_right_axis     :integer          default(0)
#  distance_left_sph       :decimal(10, 2)   default(0.0)
#  distance_left_cyl       :decimal(10, 2)   default(0.0)
#  distance_left_axis      :integer          default(0)
#  distance_ipd            :decimal(10, 2)   default(0.0)
#  distance_lens_color     :string(255)
#  distance_frame          :string(255)
#  distance_lens_type      :string(255)
#  near_right_sph          :decimal(10, 2)   default(0.0)
#  near_right_cyl          :decimal(10, 2)   default(0.0)
#  near_right_axis         :integer          default(0)
#  near_left_sph           :decimal(10, 2)   default(0.0)
#  near_left_cyl           :decimal(10, 2)   default(0.0)
#  near_left_axis          :integer          default(0)
#  near_ipd                :decimal(10, 2)   default(0.0)
#  near_lens_color         :string(255)
#  near_frame              :string(255)
#  near_lens_type          :string(255)
#  intermediate_right_sph  :decimal(10, 2)   default(0.0)
#  intermediate_right_cyl  :decimal(10, 2)   default(0.0)
#  intermediate_right_axis :integer          default(0)
#  intermediate_left_sph   :decimal(10, 2)   default(0.0)
#  intermediate_left_cyl   :decimal(10, 2)   default(0.0)
#  intermediate_left_axis  :integer          default(0)
#  intermediate_ipd        :decimal(10, 2)   default(0.0)
#  intermediate_lens_color :string(255)
#  intermediate_frame      :string(255)
#  intermediate_lens_type  :string(255)
#  bifocal                 :string(255)
#  height                  :decimal(10, 2)   default(0.0)
#  comments                :string(255)
#  invoice                 :decimal(10, 2)   default(0.0)
#  payment_on_account      :decimal(10, 2)   default(0.0)
#  balance_due             :decimal(10, 2)   default(0.0)
#  doctor_name             :string(255)
#  client_id               :integer
#  created_at              :datetime
#  updated_at              :datetime
#  prescription_date       :date
#

# -*- encoding : utf-8 -*-
class WorkOrder < ActiveRecord::Base
  attr_accessible :description, :date, :delivery_date, :distance_right_sph, :distance_right_cyl, :distance_right_axis, :distance_left_sph, :distance_left_cyl, :distance_left_axis, :distance_lens_color, :distance_frame, :distance_lens_type, :distance_ipd, :intermediate_right_sph, :intermediate_right_cyl, :intermediate_right_axis, :intermediate_left_sph, :intermediate_left_cyl, :intermediate_left_axis, :intermediate_lens_color, :intermediate_frame, :intermediate_lens_type, :intermediate_ipd, :near_right_sph, :near_right_cyl, :near_right_axis, :near_left_sph, :near_left_cyl, :near_left_axis, :near_lens_color, :near_frame, :near_lens_type, :near_ipd, :bifocal, :height, :comments, :doctor_name, :prescription_date, :invoice, :payment_on_account
  cattr_reader :per_page
  @@per_page = 10

  belongs_to :client
  before_save :compute_balance_due
  before_create :compute_order_number

  validates_presence_of :client

  def compute_balance_due
    self.balance_due = self.invoice.to_i - self.payment_on_account.to_i
  end

  def compute_order_number
    old_number = WorkOrder.maximum(:order_number) || 0
    self.order_number = old_number + 1
  end

  def self.search(search, page)
    where(
        'description LIKE ? OR order_number LIKE ? OR clients.name LIKE ? OR clients.address LIKE ? OR clients.phone_number LIKE ? OR clients.city LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"
    ).includes(:client).references(:clients).paginate(:page => page)
  end
end

app/controllers/work_orders_controller.rb
# -*- encoding : utf-8 -*-
class WorkOrdersController < ApplicationController

  before_filter :find_client

  # GET /work_orders
  # GET /work_orders.xml
  def index
    @work_orders = @client.work_orders.search params[:search], params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @work_orders }
    end
  end

  # GET /work_orders/1
  # GET /work_orders/1.xml
  def show
    @work_order = WorkOrder.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @work_order }
    end
  end

  # GET /work_orders/new
  # GET /work_orders/new.xml
  def new
    @work_order = WorkOrder.new
    @work_order.client = @client

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @work_order }
    end
  end

  # GET /work_orders/1/edit
  def edit
    @work_order = WorkOrder.find(params[:id])
  end

  # POST /work_orders
  # POST /work_orders.xml
  def create
    @work_order = WorkOrder.new(params[:work_order])
    @work_order.client = @client
     
    respond_to do |format|
      if @work_order.save
        flash[:notice] = 'La órden de trabajo ha sido creada con éxito.'
        format.html { redirect_to([@client, @work_order]) }
        format.xml  { render :xml => @work_order, :status => :created, :location => @work_order }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @work_order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /work_orders/1
  # PUT /work_orders/1.xml
  def update
    @work_order = WorkOrder.find(params[:id])
    @work_order.client = @client

    respond_to do |format|
      if @work_order.update_attributes(params[:work_order])
        flash[:notice] = 'La órden de trabajo ha sido editada con éxito.'
        format.html { redirect_to([@client, @work_order]) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @work_order.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /work_orders/1
  # DELETE /work_orders/1.xml
  def destroy
    @work_order = @client.work_orders.find(params[:id])
    @work_order.destroy

    respond_to do |format|
      format.html { redirect_to(work_orders_url) }
      format.xml  { head :ok }
    end
  end

  def find_items
    @work_orders = @client.work_orders.search params[:search], params[:page]
    render :partial => 'search'
  end

  def find_client
    @client = Client.where(id: params[:client_id]).first
    redirect_to clients_url unless @client
  end

  def import_file
    fichero = params[:import_file]
    if fichero.blank?
      flash[:warning] = 'Debe seleccionar un fichero'
      redirect_to :back
      return
    end
    csv_data = fichero.read
    grid = CSV::Reader.parse(csv_data, ',').to_a[1..-1]
    total_cargadas = 0
    total_ignoradas = 0
    errores = Array.new

    grid.each_with_index do |current_row, numero_fila|
      errores_fila = Array.new
      if current_row[0].blank?
        errores_fila << 'Debe especificar un cliente'
        errores << {:fila => numero_fila + 1, :mensajes => errores_fila}
        total_ignoradas += 1
        next
      end
      client = Client.first(
          :conditions => {
              :name => current_row[0],
              :surname => current_row[1],
              :phone_number => current_row[40]
          }
      )
      if client.blank?
        client = Client.new(
            :name => current_row[0],
            :surname => current_row[1],
            :phone_number => current_row[40]
        )
        if client.valid?
          client.save
        else
          errores << {:fila => numero_fila + 1, :mensajes => client.errors.full_messages.collect {|i| 'Cliente: ' + i}}
          total_ignoradas += 1
          next
        end
      end

      date = current_row[2].to_date rescue nil
      date += 2000.years if !date.nil? && date.year < 2000

      delivery_date = current_row[3].to_date rescue nil
      delivery_date += 2000.years if !delivery_date.nil? && delivery_date.year < 2000

      prescription_date = current_row[41].to_date rescue nil
      prescription_date += 2000.years if !prescription_date.nil? && prescription_date.year < 2000

      work_order = client.work_orders.build(
          :description => current_row[1],
          :date => date,
          :delivery_date => delivery_date,
          :distance_right_sph => current_row[4],
          :distance_right_cyl => current_row[5],
          :distance_right_axis => current_row[6],
          :distance_left_sph => current_row[7],
          :distance_left_cyl => current_row[8],
          :distance_left_axis => current_row[9],
          :distance_lens_color => current_row[10],
          :distance_frame => current_row[11],
          :distance_lens_type => current_row[12],
          :distance_ipd => current_row[13],
          :intermediate_right_sph => current_row[14],
          :intermediate_right_cyl => current_row[15],
          :intermediate_right_axis => current_row[16],
          :intermediate_left_sph => current_row[17],
          :intermediate_left_cyl => current_row[18],
          :intermediate_left_axis => current_row[19],
          :intermediate_lens_color => current_row[20],
          :intermediate_frame => current_row[21],
          :intermediate_lens_type => current_row[22],
          :intermediate_ipd => current_row[23],
          :near_right_sph => current_row[24],
          :near_right_cyl => current_row[25],
          :near_right_axis => current_row[26],
          :near_left_sph => current_row[27],
          :near_left_cyl => current_row[28],
          :near_left_axis => current_row[29],
          :near_lens_color => current_row[30],
          :near_frame => current_row[31],
          :near_lens_type => current_row[32],
          :near_ipd => current_row[33],
          :bifocal => current_row[34],
          :height => current_row[35],
          :comments => current_row[36],
          :doctor_name => current_row[37],
          :invoice => current_row[38],
          :payment_on_account => current_row[39],
          :prescription_date => prescription_date
      )
      if work_order.valid?
        work_order.save
        total_cargadas += 1
      else
        errores << {:fila => numero_fila + 1, :mensajes => work_order.errors.full_messages}
        total_ignoradas += 1
      end
    end

    if errores.blank?
      flash[:notice] =  "Los datos se han importado con éxito.<br>Se han cargado #{total_cargadas} entradas.<br>Se han ignorado #{total_ignoradas} entradas."
    else
      mensaje = "Algunos datos no se han podido cargar debido a errores.<br>"
      mensaje += "Se han cargado #{total_cargadas} entradas.<br>Se han ignorado #{total_ignoradas} entradas.<br>"
      mensaje += "#{errores.size} entradas no se han podido cargar debido a errores.<br>Los errores son los siguientes:<br>"
      mensaje += '<ul>' + errores.collect {|i| "<li>En la fila #{i[:fila]}:</li>" + '<ul>' + i[:mensajes].collect{|j| '<li>' + j + '</li>'}.join + '</ul>'}.join + '</ul>'
      flash[:warning] =  mensaje
    end
    redirect_to :controller => :main
  end
end

app/views/work_orders/_search.html.erb
<div class="table-responsive">
  <table class="table table-striped">
    <tr>
      <th>Client</th>
      <th>Descripción</th>
      <th>Fecha de creación</th>
      <th>Fecha de actualización</th>
      <th colspan="3">Acciones</th>
    </tr>

    <% for work_order in @work_orders %>
        <tr>
          <td><%= h work_order.client.name %></td>
          <td><%= h work_order.description %></td>
          <td><%= h work_order.created_at.to_date %></td>
          <td><%= h work_order.updated_at.to_date %></td>
          <td><%= link_to 'Ver', [@client, work_order] %></td>
          <td><%= link_to 'Editar', edit_client_work_order_path(@client, work_order) %></td>
          <td><%= link_to 'Borrar', [@client, work_order], data: {confirm: "¿Está seguro de borrar la orden #{work_order.description}?"}, :method => :delete %></td>
        </tr>
    <% end %>
  </table>
</div>

<% params[:action] = "index" %>
<%= will_paginate @work_orders, :prev_label => "&laquo; Anterior", :next_label => "Siguiente &raquo;" %>

app/views/work_orders/edit.html.erb
<% @title = "Editar órden de trabajo" %>
<% @navbar = [link_to('<span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Clients'.html_safe, clients_path), link_to('<span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;Órdenes de trabajo'.html_safe, client_work_orders_path(@client)), @title] %>

<%= error_messages_for :work_order %>

<div class="table-responsive tblclient">
  <%= form_for([@client, @work_order]) do |form| %>
      <%= render :partial => 'form', :object => form %>
      <%= form.submit 'Guardar edición órden', :class => 'btn btn-warning pull-right' %>
      <%= link_to '<span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;&nbsp;Volver atrás'.html_safe, client_work_orders_path %>
  <% end %>
</div>

app/views/work_orders/index.html.erb
<% @title = "Órdenes de trabajo" %>
<% @navbar = [link_to('<span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Clients'.html_safe, clients_path), '<span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;Órdenes de trabajo'.html_safe ] %>

<%= link_to 'Nueva órden de trabajo', new_client_work_order_path(@client), :class => 'btn btn-warning pull-right' %>
<%= render :partial => "shared/search_field" %>
<div id="search_results">
  <%= render :partial => "search" %>
</div>

app/views/work_orders/new.html.erb
<% @title = "Nueva órden de trabajo" %>
<% @navbar = [link_to('<span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Clients'.html_safe, clients_path), link_to('<span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;Órdenes de trabajo'.html_safe, client_work_orders_path(@client)), @title ] %>

<%= error_messages_for :work_order %>

<div class="table-responsive tblclient">
    <%= form_for([@client, @work_order]) do |form| %>
      <%= render :partial => 'form', :object => form %>
      <%= form.submit 'Crear', :class => 'btn btn-warning pull-right' %>
    <% end %>

    <%= link_to '<span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;&nbsp;Volver atrás'.html_safe, client_work_orders_path %>
</div>

app/views/work_orders/show.html.erb
<% @title = "Mostrar órden de trabajo" %>
<% @navbar = [link_to('<span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Clients'.html_safe, clients_path), link_to('<span class="glyphicon glyphicon-list-alt"></span>&nbsp;&nbsp;Órdenes de trabajo'.html_safe, client_work_orders_path(@client)), @title] %>

<div class="table-responsive tblclient">
  <div>
    <%= link_to '<span class="print_link glyphicon glyphicon-print"></span>&nbsp;&nbsp;Imprimir órden de trabajo'.html_safe, 'javascript:window.print()' %>
  </div>
  <br />
  <table class="table table-striped">
    <tr>
      <td><b>Fecha de creación:</b></td>
      <td><b><%= @work_order.created_at.to_date %></b></td>
    </tr>
    <tr>
      <td><b>Fecha de actualización:</b></td>
      <td><%= @work_order.updated_at.to_date %></td>
    </tr>
    <tr>
      <td><b>Número de órden:</b></td>
      <td><%= @work_order.order_number %></td>
    </tr>
    <tr>
      <td><b>Client:</b></td>
      <td><%= @work_order.client.name %></td>
    </tr>
    <tr>
      <td><b>Descripción:</b></td>
      <td><%= @work_order.description %></td>
    </tr>
    <tr>
      <td><b>Fecha:</b></td>
      <td><%= @work_order.date %></td>
    </tr>
    <tr>
      <td><b>Para el día:</b></td>
      <td><%= @work_order.delivery_date %></td>
    </tr>
    <tr>
      <td colspan="2"><br/>
        <hr/>
        <br/></td>
    </tr>
    <tr>
      <td colspan="2"><b>LEJOS</b></td>
    </tr>
    <tr>
      <td><b>Ojo derecho:</b></td>
      <td>
        <table>
          <tr>
            <td>Esf.</td>
            <td><%= '%+.2f' % @work_order.distance_right_sph %></td>
            <td>Cil.</td>
            <td><%= '%+.2f' % @work_order.distance_right_cyl %></td>
            <td>en</td>
            <td><%= @work_order.distance_right_axis %></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td><b>Ojo izquierdo:</b></td>
      <td>
        <table>
          <tr>
          <tr>
            <td>Esf.</td>
            <td><%= '%+.2f' % @work_order.distance_left_sph %></td>
            <td>Cil.</td>
            <td><%= '%+.2f' % @work_order.distance_left_cyl %></td>
            <td>en</td>
            <td><%= @work_order.distance_left_axis %></td>
          </tr>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td><b>Color:</b></td>
      <td><%= @work_order.distance_lens_color %></td>
    </tr>
    <tr>
      <td><b>Armazón Art.:</b></td>
      <td><%= @work_order.distance_frame %></td>
    </tr>
    <tr>
      <td><b>Tipo de lente:</b></td>
      <td><%= @work_order.distance_lens_type %></td>
    </tr>
    <tr>
      <td><b>Distancia interpupilar:</b></td>
      <td><%= @work_order.distance_ipd %></td>
    </tr>
    <tr>
      <td colspan="2"><br/>
        <hr/>
        <br/></td>
    </tr>
    <tr>
      <td colspan="2"><b>INTERMEDIO</b></td>
    </tr>
    <tr>
      <td><b>Ojo derecho:</b></td>
      <td>
        <table>
          <tr>
            <td>Esf.</td>
            <td><%= '%+.2f' % @work_order.intermediate_right_sph %></td>
            <td>Cil.</td>
            <td><%= '%+.2f' % @work_order.intermediate_right_cyl %></td>
            <td>en</td>
            <td><%= @work_order.intermediate_right_axis %></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td><b>Ojo izquierdo:</b></td>
      <td>
        <table>
          <tr>
          <tr>
            <td>Esf.</td>
            <td><%= '%+.2f' % @work_order.intermediate_left_sph %></td>
            <td>Cil.</td>
            <td><%= '%+.2f' % @work_order.intermediate_left_cyl %></td>
            <td>en</td>
            <td><%= @work_order.intermediate_left_axis %></td>
          </tr>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td><b>Color:</b></td>
      <td><%= @work_order.intermediate_lens_color %></td>
    </tr>
    <tr>
      <td><b>Armazón Art.:</b></td>
      <td><%= @work_order.intermediate_frame %></td>
    </tr>
    <tr>
      <td><b>Tipo de lente:</b></td>
      <td><%= @work_order.intermediate_lens_type %></td>
    </tr>
    <tr>
      <td><b>Distancia interpupilar:</b></td>
      <td><%= @work_order.intermediate_ipd %></td>
    </tr>
    <tr>
      <td colspan="2"><br/>
        <hr/>
        <br/></td>
    </tr>
    <tr>
      <td colspan="2"><b>CERCA</b></td>
    </tr>
    <tr>
      <td><b>Ojo derecho:</b></td>
      <td>
        <table>
          <tr>
            <td>Esf.</td>
            <td><%= '%+.2f' % @work_order.near_right_sph %></td>
            <td>Cil.</td>
            <td><%= '%+.2f' % @work_order.near_right_cyl %></td>
            <td>en</td>
            <td><%= @work_order.near_right_axis %></td>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td><b>Ojo izquierdo:</b></td>
      <td>
        <table>
          <tr>
          <tr>
            <td>Esf.</td>
            <td><%= '%+.2f' % @work_order.near_left_sph %></td>
            <td>Cil.</td>
            <td><%= '%+.2f' % @work_order.near_left_cyl %></td>
            <td>en</td>
            <td><%= @work_order.near_left_axis %></td>
          </tr>
          </tr>
        </table>
      </td>
    </tr>
    <tr>
      <td><b>Color:</b></td>
      <td><%= @work_order.near_lens_color %></td>
    </tr>
    <tr>
      <td><b>Armazón Art.:</b></td>
      <td><%= @work_order.near_frame %></td>
    </tr>
    <tr>
      <td><b>Tipo de lente:</b></td>
      <td><%= @work_order.near_lens_type %></td>
    </tr>
    <tr>
      <td><b>Distancia interpupilar:</b></td>
      <td><%= @work_order.near_ipd %></td>
    </tr>
    <tr>
      <td colspan="2"><br/>
        <hr/>
        <br/></td>
    </tr>
    <tr>
      <td><b>Bifocal:</b></td>
      <td><%= @work_order.bifocal %></td>
    </tr>
    <tr>
      <td><b>Altura:</b></td>
      <td><%= @work_order.height %></td>
    </tr>
    <tr>
      <td colspan="2"><br/>
        <hr/>
        <br/></td>
    </tr>
    <tr>
      <td valign="top"><b>Observaciones:</b></td>
      <td><%= @work_order.comments %></td>
    </tr>
    <tr>
      <td><b>Receta Dr:</b></td>
      <td><%= @work_order.doctor_name %></td>
    </tr>
    <tr>
      <td><b>Fecha de la receta:</b></td>
      <td><%= @work_order.prescription_date %></td>
    </tr>
    <tr>
      <td><b>Total:</b></td>
      <td><%= number_to_currency @work_order.invoice %></td>
    </tr>
    <tr>
      <td><b>Seña:</b></td>
      <td><%= number_to_currency @work_order.payment_on_account %></td>
    </tr>
    <tr>
      <td><b>Saldo:</b></td>
      <td><%= number_to_currency @work_order.balance_due %></td>
    </tr>
  </table>
  <div class="print_link">
    <%= link_to '<span class="glyphicon glyphicon-circle-arrow-left"></span>&nbsp;&nbsp;Volver atrás'.html_safe, client_work_orders_path %>
    <%= link_to 'Editar órden de trabajo', edit_client_work_order_path(@client, @work_order), :class => 'btn btn-warning pull-right' %>
  </div>
</div>