config/routes.rb
GestionOpticaArena::Application.routes.draw do
  devise_for :users
  resources :work_orders do
    collection do
      get :find_items
      get :import_file
    end
  end

  resources :clients do
    collection do
      get :find_items
    end
    resources :work_orders
  end

  root :to => 'main#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8"/>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <link href="https://fonts.googleapis.com/css?family=Baloo+Paaji|Roboto" rel="stylesheet">
  <%= favicon_link_tag "favicon.png?v=#{Time.now.to_i}", type: 'image/png' %>
  <%= stylesheet_link_tag 'application', :media => :screen %>
  <%= stylesheet_link_tag 'application-print', :media => :print %>
  <%= javascript_include_tag 'application' %>
  <!--[if gte IE 5]>
    <%= stylesheet_link_tag "application-ie", :media => :screen %>
    <![endif]-->
  <title>
    <%=
        if @title then
          site_name + ' - ' + @title
        else
          site_name
        end
    %>
  </title>
</head>
<body>
<div class="container">
  <header>
    <div class="header-session text-right round">
      <% if user_signed_in? %>
          <%= t('Logged in as') %> <strong><%= current_user.try(:email) %></strong>.
          <%= link_to t('Edit profile'), edit_user_registration_path, :class => 'navbar-link' %>
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> |
          <%= link_to t('Logout'), destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
          <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
      <% else %>
          <%= link_to t('Sign up'), new_user_registration_path, :class => 'navbar-link' %>
          <span class="glyphicon glyphicon-file" aria-hidden="true"></span> |
          <%= link_to t('Login'), new_user_session_path, :class => 'navbar-link' %>
          <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
      <% end %>
    </div>
    <div class="header round">
      <div class="title"><h2><%= site_name %></h2></div>
      <div class="logo img-rounded"></div>
    </div>
  </header>
  <div class="main row">
    <div class="col-md-12 alert-box">
      <p class="navbar-text">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      </p>
    </div>
    <div class="row">
      <% if user_signed_in? %>
          <div class="col-md-3 menu">
            <nav class="navbar navbar-default navbar-left menu-left">
              <div class="list-group">
                <h3><%= t('clients').upcase %></h3>
                <ul class="nav nav-pills nav-stacked">
                  <%= nav_link t('new').capitalize + " " + t('client'), new_client_path, {:class => 'list-group-item'} %>
                  <%= nav_link t('show').capitalize + " " + t('clients'), clients_path, {:class => 'list-group-item'} %>
                  <%= nav_link t('import_wo').capitalize, import_file_work_orders_path, {:class => 'list-group-item'} %>
                </ul>
              </div>
            </nav>
          </div>
      <% end %>
      <div class="col-md-9">
        <aside>
          <div>
            <%= yield %>
          </div>
        </aside>
      </div>
    </div>
  </div>

  <div class="clearfix"></div>
  <br/><br/>

  <div class="panel-footer footer text-center round">
    <footer class="round">
      <span class="left copyleft">
        <strong>2007&nbsp;-&nbsp;<%= Date.today.year %>.</strong>
        <script type="text/javascript">
            emailE = ('dev@' + 'karinaarena.com.ar')
            document.write(
                    '<a id="mail" href="mailto:' + emailE + '">KPA</a>'
            )
        </script>.
      </span>
    </footer>
  </div>
</div>
</body>
</html>